### ISSUE TITLE
renderFile cannot handles paths generated from import.meta.url

### ISSUE THREAD

**Issue by zhmushan** [syumai/dejs#38]
```ts
import { join } from "https://deno.land/std/path/mod.ts";
import { renderFile } from "https://deno.land/x/dejs/mod.ts";
const { stdout, copy } = Deno;

const output = await renderFile(join(import.meta.url, "../index.html"), {});
await copy(stdout, output);
```

output:
```
error: Uncaught NotFound: The system cannot find the path specified. (os error 3)
► $deno$/ops/dispatch_json.ts:43:11
    at NotFound ($deno$/errors.ts:75:5)
    at unwrapResponse ($deno$/ops/dispatch_json.ts:43:11)
    at sendAsync ($deno$/ops/dispatch_json.ts:98:10)
```

I think it is caused by the parameter carrying the "file:/" prefix. Is it as expected?

**Comment by syumai** [comment]
I'll check this later 👍

**Comment by syumai** [comment]
Deno's open or fetch doesn't look like supports `file:` scheme.
Error you specified is returned from simple `open` call.
Maybe this problem needs to be considered separately from dejs.

**Comment by syumai** [comment]
@zhmushan 
For mac or linux, helper function like below works.

```ts

const trimFileScheme = (path: string): string => {
  return path.replace(/^file:\/+/, "/");
};

const originalFilePath = join(import.meta.url, "../index.html");
console.log(originalFilePath); // => file:/home/syumai/src/deno/dejs/example/importmeta/src/index.html


const filePath = trimFileScheme(originalFilePath);
console.log(filePath); // => /home/syumai/src/deno/dejs/example/importmeta/src/index.html

const output = await renderFile(filePath, {});
await copy(stdout, output);
```

**Comment by syumai** [comment]
If this feature is considered to be added to this module, the function names will be `renderFileRelative` and `includeRelative`.

**Comment by zhmushan** [comment]
@syumai 
Thanks to your replay, I used your method and the problem has been solved.

**Comment by syumai** [comment]
Then I close this issue.
