### ISSUE TITLE
SyntaxError: Unexpected identifier '$$OUTPUT' + SyntaxError: Unexpected token ')'`

### ISSUE THREAD

**Issue by waptik** [syumai/dejs#79]
Hi. I'm new to the whole deno ecosystem and wanted to port some npm packages to deno.

I decided to port https://github.com/cpiber/epub-gen-memory  and came across your project.

I have been facing some issues along the way. I've never tried ejs before.

So i created a new branch of the project just for this issue which is at https://github.com/waptik/epubgen/tree/dejs-issue.

When i run `deno task test`, i get `error: (in promise) SyntaxError: Unexpected token ')'` as error and i think it's got to do with js statements that have `(` & `)` like an `if(...)` statement. Because when i comment https://github.com/waptik/epubgen/blob/dejs-issue/epub.ts#L173-#L201 and uncomment https://github.com/waptik/epubgen/blob/dejs-issue/epub.ts#L160-#L165 and i remove `<navMap> ... </navMap>` from `toc.ncx.ejs`(if i don't remove it, i get the error for this issue's title), the epub file is generated successfully.

<details>
<summary>Full logs</summary>

Warning deno task is unstable and may drastically change in the future
Task test deno test --unstable -A --allow-read --allow-write  --allow-env --allow-run --allow-hrtime ./tests/mod.ts
Check file:///home/waptik/code/deno/epubgen/tests/mod.ts
running 1 test from ./tests/mod.ts
download.epub ...
------- output -------
{
  template: {
    path: "/home/waptik/code/deno/epubgen/templates/ejs",
    ejs: { rmWhitespace: true }
  }
}
Generating Template Files...
Downloading fonts...
No fonts to download
Downloading images...
Uncaught error from ./tests/mod.ts FAILED
download.epub ... cancelled (0ms)

 ERRORS 

./tests/mod.ts (uncaught error)
error: (in promise) SyntaxError: Unexpected token ')'
      const f = new Function(...Object.keys(args), src);
                ^
    at new Function (<anonymous>)
    at https://deno.land/x/dejs@0.10.3/mod.ts:82:17
    at new Promise (<anonymous>)
    at https://deno.land/x/dejs@0.10.3/mod.ts:69:11
    at renderFileToString (https://deno.land/x/dejs@0.10.3/mod.ts:202:10)
    at async EPub.generateTemplateFiles (file:///home/waptik/code/deno/epubgen/epub.ts:174:19)
This error was not caught from a test and caused the test runner to fail on the referenced module.
It most likely originated from a dangling promise, event/timeout handler or top-level code.

 FAILURES 

./tests/mod.ts (uncaught error)

FAILED | 0 passed | 2 failed (311ms)

error: Test failed

</details>

Deno version: 1.25.0+c3e48cb
dejs Version: 0.10.3

**Comment by waptik** [comment]
So i managed to fix the issue by using the appropriate control flow mentioned in https://github.com/syumai/dejs#supported.
It looks like i missed it.

Thanks anayway
